# Generated by Django 3.1.7 on 2021-03-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=150)),
                ('code_matricule', models.CharField(max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'chauffeur',
                'verbose_name_plural': 'chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'motif',
                'verbose_name_plural': 'motifs',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_releve', models.CharField(max_length=20, verbose_name='Numéro de relevé')),
                ('code_vehicule', models.CharField(max_length=50, null=True, verbose_name='Code véhicule')),
                ('code_remorque', models.CharField(max_length=50, verbose_name='Code remorque')),
                ('imat_vehicule', models.CharField(max_length=50, verbose_name='Imat. véhicule')),
                ('imat_remorque', models.CharField(max_length=50, verbose_name='Imat. Remorque')),
                ('date_frais', models.DateField(null=True, verbose_name='Date de frais')),
                ('date_demande', models.DateTimeField(verbose_name='Date de demande')),
                ('code_activite', models.CharField(choices=[('DGE', 'DGE'), ('DCF', 'DCF'), ('DRH', 'DRH'), ('DEX', 'DEX'), ('DET', 'DET'), ('DCM', 'DCM'), ('SMG', 'SMG'), ('FHY', 'FHY'), ('FSB', 'FSB'), ('FHP', 'FHP'), ('FTC', 'FTC'), ('FCS', 'FCS'), ('FDI', 'FDI'), ('LEV', 'LEV'), ('LOC', 'LOC'), ('SDI', 'SDI'), ('RAV', 'RAV'), ('PAF', 'PAF'), ('COL', 'COL')], max_length=150, verbose_name='Code Activité')),
                ('libelle_activite', models.CharField(choices=[('DGE', 'Dir. Générale(DGE)'), ('DCF', 'Dir. Financière(DCF)'), ('DRH', 'Dir. RH(DRH)'), ('DEX', 'Dir. Exploitation(DEX)'), ('DET', 'Dir. Technique(DET)'), ('DCM', 'Dir. Commerciale(DCM)'), ('SMG', 'Moyens Generaux(SMG)'), ('FHY', 'fret Hydrocarbure(FHY)'), ('FSB', 'fret boisson(FSB)'), ('FHP', 'fret huile de palm(FHP)'), ('FTC', 'fret conteneurs(FTC)'), ('FCS', 'fret canne à sucre(FCS)'), ('FDI', 'fret divers(FDI)'), ('LEV', 'levage(LEV)'), ('LOC', 'location de surfaces(LOC)'), ('SDI', 'services divers(SDI)'), ('RAV', 'revenus à ventiler(RAV)'), ('PAF', 'Prestation Accessoir(PAF)'), ('COL', 'fret Colis lourds(COL)')], max_length=255, verbose_name='Libelle')),
                ('quantite', models.IntegerField(default=1)),
                ('pu', models.FloatField(default=0.0, verbose_name='Prix unitaire')),
                ('total', models.FloatField()),
                ('urgence', models.CharField(choices=[('A Exécuter Immediatement', 'A Exécuter Immediatement'), ('A Exécuter Dans Les Plus Brefs Délais', 'A Exécuter Dans Les Plus Brefs Délais'), ('Peut Etre Reporté', 'Peut Etre Reporté')], max_length=255)),
                ('traite', models.BooleanField(default=False)),
                ('agence', models.CharField(choices=[('0000', 'Siège'), ('0001', 'Abidjan (agence principale)'), ('0002', 'Bouaflé'), ('0003', 'San-Pedro'), ('0007', 'Bouaké'), ('0008', 'Yamoussoukro'), ('0009', 'Ferké'), ('0010', 'Minautores')], max_length=255)),
                ('axe_analyse', models.CharField(choices=[('200', 'Batiment et charge locative'), ('210', 'Voyage & deplacement'), ('220', 'Fourniture & consommable de bureau'), ('230', 'Charge personnel'), ('240', 'Quote-part depreciation immo'), ('250', 'Personnel & services exterieur'), ('260', 'Relation exterieur'), ('270', 'Impôt & taxes'), ('280', 'Autres charges directions et service'), ('900', "Recette d'exploitation"), ('910', 'Frais/Opération (frais voyages)'), ('920', 'Papier administratif-CR'), ('930', "Main d'oevre dédiée"), ('940', 'Quote-part amortissement CR et autres'), ('950', 'Entretien & reparation CR'), ('960', 'Frais generaux')], max_length=255)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demande.chauffeur')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nom du demandeur')),
                ('motif', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demande.motif', verbose_name='MOTIF')),
            ],
        ),
    ]
