# Generated by Django 3.1.7 on 2021-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='a_rembourser',
            field=models.BooleanField(default=False),
        ),
    ]
