# Generated by Django 3.1.7 on 2021-04-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_auto_20210329_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_demande',
            field=models.DateField(verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_frais',
            field=models.DateField(null=True, verbose_name='Date de frais'),
        ),
    ]
